export enum SubjectExceptionCodeEnum {
  NO_PERMISSION_TO_VIEW_SUBJECTS = 'NO_PERMISSION_TO_VIEW_SUBJECTS',
  NO_PERMISSION_TO_EDIT_SUBJECTS = 'NO_PERMISSION_TO_EDIT_SUBJECTS',
  SUBJECT_NOT_FOUNT = 'SUBJECT_NOT_FOUNT',
}
